#!/bin/sh
# blist: Play a playlist in the playlist directory

_ammend () {
	if [ -z $opts ]; then
		opts="$1"
	else
		opts="$opts $1"
	fi
}

_basename () {
	sed 's=.*/=='
}

if [ -z $1 ]; then
	list=$(blistdb -m)
else
	list=$(blistread $@)
fi
[ -z "$list" ] && exit 0

cutlist=$(echo "$list" | _basename)

echo "$cutlist"
echo

while printf "${opts:+  options: $opts\n}${startat:+  start at: $startat\n}(h for help): "; do
	read -r command
	echo
	case "$command" in 
		h)
			echo 'h: display this menu'
			echo 'p: print the playlist'
			echo 'P: print the playlist inside your pager'
			echo 'r: repeat the playlist'
			echo 's: shuffle the playlist'
			echo 'search term: select the song to start at'
			echo 'enter: play'
			echo 'q: quit'
			echo
			;;
		p)
			echo
			echo "$cutlist"
			echo
			;;
		P)
			echo "$cutlist" | ${PAGER:-less}
			;;
		r)
			if [ -z $loop ]; then
				loop=-r
				_ammend repeat
			fi
			;;
		s)
			if [ -z $shuffle ]; then
				shuflle=-s
				_ammend shuffle
			fi
			;;
		q)
			exit 0
			;;
		"")
			break
			;;
		*)
			possible=1
			while read song; do
				case $song in
					*$command*)
						startat="$song"
						startpos="-b $possible"
						break
				esac
				possible=$((possible + 1))
			done <<-EOF
			$cutlist
			EOF
			;;
	esac
done
exec blister $loop $shuflle $startpos "$list"

exit 0
